/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/asistente.gltf -o ./components/Asistentados.jsx -r public 
*/

import React, { use, useRef, useEffect } from 'react'
import { useFBX, useGLTF, useAnimations } from '@react-three/drei'

export function Asistenta(props) {
  const { nodes, materials } = useGLTF('/asistente.gltf')
  const { animations } = useFBX('animation/idle.fbx')
  animations[0].name='idle'
  console.log(animations)
  // Apply animation to model
  const group = useRef()
  const { actions } = useAnimations(animations, group)
  
  useEffect(() => {
    actions.idle.play()
  } , [actions.idle])
  

  return (
    <group {...props} dispose={null} ref={group}>
      <mesh geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} />
      <mesh geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} />
      <mesh geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} />
      <mesh geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} />
      <mesh geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} />
      <mesh geometry={nodes.Wolf3D_Glasses.geometry} material={materials.Wolf3D_Glasses} />
      <mesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} />
      <mesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} />
      <mesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} />
      <mesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} />
    </group>
  )
}

useGLTF.preload('/asistente.gltf')
