/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/asis.glb -o ./components/Asis.jsx -r public 
*/

import React, { useRef } from 'react'
import { useFBX, useGLTF, useAnimations } from '@react-three/drei'

export function Asis(props) {
  const { nodes, materials } = useGLTF('/asis.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.Wolf3D_Body001.geometry} material={materials['Wolf3D_Body.002']} skeleton={nodes.Wolf3D_Body001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Glasses001.geometry} material={materials['Wolf3D_Glasses.002']} skeleton={nodes.Wolf3D_Glasses001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Hair001.geometry} material={materials['Wolf3D_Hair.002']} skeleton={nodes.Wolf3D_Hair001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom001.geometry} material={materials['Wolf3D_Outfit_Bottom.002']} skeleton={nodes.Wolf3D_Outfit_Bottom001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear001.geometry} material={materials['Wolf3D_Outfit_Footwear.002']} skeleton={nodes.Wolf3D_Outfit_Footwear001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top001.geometry} material={materials['Wolf3D_Outfit_Top.002']} skeleton={nodes.Wolf3D_Outfit_Top001.skeleton} />
      <skinnedMesh geometry={nodes.EyeLeft001.geometry} material={materials['Wolf3D_Eye.003']} skeleton={nodes.EyeLeft001.skeleton} />
      <skinnedMesh geometry={nodes.EyeRight001.geometry} material={materials['Wolf3D_Eye.003']} skeleton={nodes.EyeRight001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Head001.geometry} material={materials['Wolf3D_Skin.002']} skeleton={nodes.Wolf3D_Head001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Teeth001.geometry} material={materials['Wolf3D_Teeth.002']} skeleton={nodes.Wolf3D_Teeth001.skeleton} />
    </group>
  )
}

useGLTF.preload('/asis.glb')
